### ISSUE TITLE
auth = tweepy.OAuthHandler("API_KEY_9J7eWF66", "API_SECRET_39yoSEdA")

### ISSUE THREAD

**Issue by KeironO** [ExPHAT/twitter-sort#1]
auth = tweepy.OAuthHandler("API_KEY_9J7eWF66", "API_SECRET_39yoSEdA")

Wat

**Comment by ExPHAT** [comment]
no.

**Comment by KeironO** [comment]
No?

**Comment by rtgibbons** [comment]
If you have already; You want to change these. There are scripts that will pull them down and abuse them. Most only require them to be up for < 1 minute. 

While you are at it, you should clean up your other sensitive data 

i.e https://github.com/ExPHAT/code.ExPHAT.com/blob/master/app.js#L21
