### ISSUE TITLE
Possible bug in the sort assertion

### ISSUE THREAD

**Issue by cskeppstedt** [ExPHAT/twitter-sort#7]
Hello! Brilliant sort algorithm. I think I have found a potential bug.

This line:
`if not givenNumbers[i] > givenNumbers[i-1]:`
https://github.com/ExPHAT/twitter-sort/blob/master/main.py#L79

I think it should be:
`if not givenNumbers[i] >= givenNumbers[i-1]:` 

This will allow for multiple occurrence of the same number, e.g. `[1,4,5,4]`.

Best regards, Christoffer

**Comment by ExPHAT** [comment]
Awesome, fixed in 88c93a6
